sudo: required
services:
  - docker

before_install:
  - docker build -t shivanandchikkalli/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shivanandchikkalli/react-test npm test

after_success:
  - docker build -t shivanandchikkalli/multi-client ./client
  - docker build -t shivanandchikkalli/multi-nginx ./nginx
  - docker build -t shivanandchikkalli/multi-server ./server
  - docker build -t shivanandchikkalli/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push shivanandchikkalli/multi-client
  - docker push shivanandchikkalli/multi-nginx
  - docker push shivanandchikkalli/multi-server
  - docker push shivanandchikkalli/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-608972471936'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
